notifications:
 email:
  recipients:
   - pierrick.roger@gmail.com
                           
before_install:
 - sudo apt-get install -y ant
 - sudo apt-get install -y r-base
 - sudo R -e "install.packages(c('getopt', 'stringr'), dependencies = TRUE, repos='http://lib.ugent.be/CRAN/')"

script:
 - ant test
